src/Entity/Stagiaire.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\StagiaireRepository;

#[ORM\Entity(repositoryClass: StagiaireRepository::class)]
class Stagiaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $login;

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'string', length: 255)]
    private $prenom;

    #[ORM\Column(type: 'string', length: 255)]
    private $email;

    #[ORM\Column(type: 'integer')]
    private $admin_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLogin(): ?string
    {
        return $this->login;
    }

    public function setLogin(string $login): self
    {
        $this->login = $login;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAdminId(): ?int
    {
        return $this->admin_id;
    }

    public function setAdminId(int $admin_id): self
    {
        $this->admin_id = $admin_id;

        return $this;
    }


}

src/Form/StagiaireType.php
<?php
// src/Form/StagiaireType.php

namespace App\Form;

use App\Entity\Stagiaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType; // Use PasswordType for password field
use Symfony\Component\Form\Extension\Core\Type\IntegerType; // Use IntegerType for admin_id field

class StagiaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom', TextType::class)
            ->add('prenom', TextType::class)
            ->add('email', TextType::class)
            ->add('login', TextType::class)
            ->add('admin_id', IntegerType::class, [
                'attr' => ['class' => 'border rounded w-full py-2 px-3 text-gray-700'],
            ])
            ->add('password', PasswordType::class, [
                'attr' => ['class' => 'border rounded w-full py-2 px-3 text-gray-700'],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Stagiaire::class,
        ]);
    }
}

src/Controller/StagiaireController.php
<?php
namespace App\Controller;

use App\Entity\Stagiaire;
use App\Form\StagiaireType;
use App\Repository\StagiaireRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/stagiaire')]
class StagiaireController extends AbstractController
{
    #[Route('/', name: 'app_stagiaire_index', methods: ['GET'])]
    public function index(Request $request, StagiaireRepository $stagiaireRepository): Response
    {
        $searchQuery = $request->query->get('q');
        $stagiaires = $stagiaireRepository->findBySearchQuery($searchQuery);
        return $this->render('stagiaire/index.html.twig', [
            'stagiaires' => $stagiaires,
        ]);
    }

    #[Route('/new', name: 'app_stagiaire_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $stagiaire = new Stagiaire();
        $form = $this->createForm(StagiaireType::class, $stagiaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Set the default password
            $defaultPassword = '123456789';
            $stagiaire->setPassword($defaultPassword);

            $entityManager->persist($stagiaire);
            $entityManager->flush();

            $this->addFlash('success', 'New Stagiaire created with default password: ' . $defaultPassword);

            return $this->redirectToRoute('app_stagiaire_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('stagiaire/new.html.twig', [
            'stagiaire' => $stagiaire,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_stagiaire_show', methods: ['GET'])]
    public function show(Stagiaire $stagiaire): Response
    {
        if (!$stagiaire) {
            throw $this->createNotFoundException('The stagiaire does not exist');
        }
        return $this->render('stagiaire/show.html.twig', [
            'stagiaire' => $stagiaire,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_stagiaire_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Stagiaire $stagiaire, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(StagiaireType::class, $stagiaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Handle password update
            $newPassword = $form->get('password')->getData();
            if ($newPassword) {
                $stagiaire->setPassword($newPassword);
            }

            $entityManager->flush();

            return $this->redirectToRoute('app_stagiaire_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('stagiaire/edit.html.twig', [
            'stagiaire' => $stagiaire,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_stagiaire_delete', methods: ['POST'])]
    public function delete(Request $request, Stagiaire $stagiaire, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $stagiaire->getId(), $request->get('_token'))) {
            $entityManager->remove($stagiaire);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_stagiaire_index', [], Response::HTTP_SEE_OTHER);
    }


}

templates/stagiaire/_delete_form.html.twig
<form method="post" action="{{ path('app_stagiaire_delete', {'id': stagiaire.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce stagiaire ?');" class="inline-block">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ stagiaire.id) }}">
    <button class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded">Supprimer</button>
</form>

templates/stagiaire/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

{#ppppppppppppppppp#}

templates/stagiaire/edit.html.twig
{# templates/stagiaire/edit.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Modifier le Stagiaire{% endblock %}

{% block body %}
    <div class="container mx-auto px-4 py-8">
        <h1 class="text-3xl font-bold mb-6 text-gray-800">Modifier le Stagiaire</h1>
        <div class="bg-white shadow-md rounded-lg overflow-hidden p-6">
            {{ form_start(form) }}
            <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
                <div>
                    {{ form_label(form.nom, 'Nom', {'label_attr': {'class': 'block text-sm font-medium text-gray-700'}}) }}
                    {{ form_widget(form.nom, {'attr': {'class': 'mt-1 block w-full shadow-sm sm:text-lg border-black rounded-md'}}) }}
                </div>
                <div>
                    {{ form_label(form.prenom, 'Prénom', {'label_attr': {'class': 'block text-sm font-medium text-gray-700'}}) }}
                    {{ form_widget(form.prenom, {'attr': {'class': 'mt-1 block w-full shadow-sm sm:text-lg border-black rounded-md'}}) }}
                </div>
                <div>
                    {{ form_label(form.email, 'Email', {'label_attr': {'class': 'block text-sm font-medium text-gray-700'}}) }}
                    {{ form_widget(form.email, {'attr': {'class': 'mt-1 block w-full shadow-sm sm:text-lg border-black rounded-md'}}) }}
                </div>
                <div>
                    {{ form_label(form.login, 'Login', {'label_attr': {'class': 'block text-sm font-medium text-gray-700'}}) }}
                    {{ form_widget(form.login, {'attr': {'class': 'mt-1 block w-full shadow-sm sm:text-lg border-black rounded-md'}}) }}
                </div>
                <div>
                    {{ form_label(form.password, 'Mot de passe', {'label_attr': {'class': 'block text-sm font-medium text-gray-700'}}) }}
                    {{ form_widget(form.password, {'attr': {'class': 'mt-1 block w-full shadow-sm sm:text-lg border-black rounded-md'}}) }}
                </div>
                <div>
                    {{ form_label(form.admin_id, 'Admin ID', {'label_attr': {'class': 'block text-sm font-medium text-gray-700'}}) }}
                    {{ form_widget(form.admin_id, {'attr': {'class': 'mt-1 block w-full shadow-sm sm:text-lg border-black rounded-md'}}) }}
                </div>
            </div>
            <div class="mt-6 flex justify-end space-x-3">
                <button type="submit" class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded">Enregistrer</button>
                <a href="{{ path('app_stagiaire_index') }}" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded">Retour à la liste</a>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/stagiaire/index.html.twig
{# templates/stagiaire/index.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Stagiaire Index{% endblock %}

{% block body %}


    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="icon-show" viewBox="0 0 24 24">
            <path d="M15 12c0 1.654-1.346 3-3 3s-3-1.346-3-3 1.346-3 3-3 3 1.346 3 3zm9-.449s-4.252 8.449-11.985 8.449c-7.18 0-12.015-8.449-12.015-8.449s4.446-7.551 12.015-7.551c7.694 0 11.985 7.551 11.985 7.551zm-7 .449c0-2.757-2.243-5-5-5s-5 2.243-5 5 2.243 5 5 5 5-2.243 5-5z"/>
        </symbol>
        <symbol id="icon-edit" viewBox="0 0 24 24">
            <path d="M7.127 22.562l-7.127 1.438 1.438-7.128 5.689 5.69zm1.414-1.414l11.228-11.225-5.69-5.692-11.227 11.227 5.689 5.69zm9.768-21.148l-2.816 2.817 5.691 5.691 2.816-2.819-5.691-5.689z"/>
        </symbol>
        <symbol id="icon-delete" viewBox="0 0 24 24">
            <path d="M3 6v18h18v-18h-18zm5 14c0 .552-.448 1-1 1s-1-.448-1-1v-10c0-.552.448-1 1-1s1 .448 1 1v10zm5 0c0 .552-.448 1-1 1s-1-.448-1-1v-10c0-.552.448-1 1-1s1 .448 1 1v10zm5 0c0 .552-.448 1-1 1s-1-.448-1-1v-10c0-.552.448-1 1-1s1 .448 1 1v10zm4-18v2h-20v-2h5.711c.9 0 1.631-1.099 1.631-2h5.315c0 .901.73 2 1.631 2h5.712z"/>
        </symbol>
        <symbol id="icon-reset" viewBox="0 0 24 24">
            <path d="M13.5 2c-5.621 0-10.211 4.443-10.475 10h-3.025l5 6.625 5-6.625h-2.975c.257-3.351 3.06-6 6.475-6 3.584 0 6.5 2.916 6.5 6.5s-2.916 6.5-6.5 6.5c-1.863 0-3.542-.793-4.728-2.053l-2.427 3.216c1.877 1.754 4.389 2.837 7.155 2.837 5.79 0 10.5-4.71 10.5-10.5s-4.71-10.5-10.5-10.5z"/>
        </symbol>
    </svg>


    <h1 class="text-2xl font-bold mb-4">Stagiaires</h1>

    <a href="{{ path('app_stagiaire_new') }}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mb-4 inline-block">Create new</a>

    {# Search Form #}
    <form action="{{ path('app_stagiaire_index') }}" method="get" class="mb-4">
        <div class="flex justify-end">
            <input type="text" name="q" placeholder="Search..." class="border rounded py-2 px-3 text-gray-700">
            <button type="submit" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded ml-2">Search</button>
        </div>
        <p class="text-gray-600 text-sm mt-2 text-right">You can search by ID, Nom, Prenom, Email, or Login.</p>
    </form>

    {# Stagiaire Table with checkboxes #}
    <form id="stagiaire-form" action="{{ path('app_stagiaire_reset_password') }}" method="post">
        {# Stagiaire Table #}
        <table class="min-w-full bg-white shadow-md rounded my-6">
            <thead>
            <tr class="bg-gray-800 text-white uppercase text-sm leading-normal">
                <th class="py-3 px-6 text-left">ID</th>
                <th class="py-3 px-6 text-left">Nom</th>
                <th class="py-3 px-6 text-left">Prenom</th>
                <th class="py-3 px-6 text-left">Email</th>
                <th class="py-3 px-6 text-left">Login</th>
                <th class="py-3 px-6 text-center">Show</th>
                <th class="py-3 px-6 text-center">Edit</th>
                <th class="py-3 px-6 text-center">Delete</th>
                <th class="py-3 px-6 text-center">Reset Password</th>
            </tr>
            </thead>
            <tbody class="text-gray-600 text-sm font-light">
            {% for stagiaire in stagiaires %}
                <tr class="border-b border-gray-200 hover:bg-gray-100">
                    <td class="py-3 px-6 text-left whitespace-nowrap">{{ stagiaire.id }}</td>
                    <td class="py-3 px-6 text-left">{{ stagiaire.nom }}</td>
                    <td class="py-3 px-6 text-left">{{ stagiaire.prenom }}</td>
                    <td class="py-3 px-6 text-left">{{ stagiaire.email }}</td>
                    <td class="py-3 px-6 text-left">{{ stagiaire.login }}</td>
                    <td class="py-3 px-6 text-center">
                        <a href="{{ path('app_stagiaire_show', {'id': stagiaire.id}) }}" class="inline-block p-1" title="Show">
                            <svg class="w-6 h-6 text-green-500 hover:text-green-700"><use xlink:href="#icon-show"></use></svg>
                        </a>
                    </td>
                    <td class="py-3 px-6 text-center">
                        <a href="{{ path('app_stagiaire_edit', {'id': stagiaire.id}) }}" class="inline-block p-1" title="Edit">
                            <svg class="w-6 h-6 text-yellow-500 hover:text-yellow-700"><use xlink:href="#icon-edit"></use></svg>
                        </a>
                    </td>
                    <td class="py-3 px-6 text-center">
                        <form method="post" action="{{ path('app_stagiaire_delete', {'id': stagiaire.id}) }}" class="inline-block">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ stagiaire.id) }}">
                            <button class="p-1" onclick="return confirm('Are you sure?');" title="Delete">
                                <svg class="w-6 h-6 text-red-500 hover:text-red-700"><use xlink:href="#icon-delete"></use></svg>
                            </button>
                        </form>
                    </td>
                    <td class="py-3 px-6 text-center">
                        <form action="{{ path('app_stagiaire_reset_password', {'id': stagiaire.id}) }}" method="POST" class="inline-block">
                            <button type="submit" class="p-1" title="Reset Password"
                                    onclick="return confirm('Are you sure that you want to reset the password?\n\nNB: The new Password is \'123456789\'');">
                                <svg class="w-6 h-6 text-blue-500 hover:text-blue-700"><use xlink:href="#icon-reset"></use></svg>
                            </button>
                        </form>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="9" class="py-3 px-6 text-center">No stagiaires found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </form>

    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">

{% endblock %}

templates/stagiaire/new.html.twig
{# templates/stagiaire/create.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Create New Stagiaire{% endblock %}

{% block body %}
    <h1 class="text-2xl font-bold mb-4">Create New Stagiaire</h1>
    {{ form_start(form) }}
    <div class="bg-white p-6 rounded-lg shadow-lg grid grid-cols-2 gap-4">
        <div>
            {{ form_row(form.nom, {'attr': {'class': 'border rounded w-full py-2 px-3 text-gray-700'}}) }}
            {{ form_row(form.prenom, {'attr': {'class': 'border rounded w-full py-2 px-3 text-gray-700'}}) }}
            {{ form_row(form.email, {'attr': {'class': 'border rounded w-full py-2 px-3 text-gray-700'}}) }}
        </div>
        <div>
            {{ form_row(form.login, {'attr': {'class': 'border rounded w-full py-2 px-3 text-gray-700'}}) }}
            {{ form_row(form.admin_id, {'attr': {'class': 'border rounded w-full py-2 px-3 text-gray-700'}}) }}
            {{ form_row(form.password, {'attr': {'class': 'border rounded w-full py-2 px-3 text-gray-700'}}) }}
        </div>
        <div class="col-span-2 mt-4">
            <p class="text-sm text-gray-600">The default password for new Stagiaire is <strong>123456789</strong>. Even you type a passWord</p>
        </div>
        <div class="col-span-2 flex justify-end mt-4">
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-2" type="submit">Save</button>
            <a href="{{ path('app_stagiaire_index') }}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Back to list</a>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock %}

{# tttttttt #}

templates/stagiaire/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails du Stagiaire{% endblock %}

{% block body %}
    <div class="container mx-auto px-4 py-8">
        <h1 class="text-3xl font-bold mb-6 text-gray-800">Détails du Stagiaire</h1>
        <div class="bg-white shadow-md rounded-lg overflow-hidden p-6">
            <dl class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2">
                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500">Nom</dt>
                    <dd class="mt-1 text-sm text-gray-900">{{ stagiaire.nom }}</dd>
                </div>
                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500">Prénom</dt>
                    <dd class="mt-1 text-sm text-gray-900">{{ stagiaire.prenom }}</dd>
                </div>
                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500">Email</dt>
                    <dd class="mt-1 text-sm text-gray-900">{{ stagiaire.email }}</dd>
                </div>

                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500">LogIn</dt>
                    <dd class="mt-1 text-sm text-gray-900">{{ stagiaire.login }}</dd>
                </div>


{#                <div class="sm:col-span-1">#}
{#                    <dt class="text-sm font-medium text-gray-500">Password</dt>#}
{#                    <dd class="mt-1 text-sm text-gray-900">{{ stagiaire.password }}</dd>#}
{#                </div>#}

                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500">Admin ID</dt>
                    <dd class="mt-1 text-sm text-gray-900">{{ stagiaire.adminId }}</dd>
                </div>
            </dl>
        </div>
        <div class="mt-6 flex space-x-3">
            <a href="{{ path('app_stagiaire_edit', {'id': stagiaire.id}) }}" class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded">Modifier</a>
            <a href="{{ path('app_stagiaire_index') }}" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded">Retour à la liste</a>
            {{ include('stagiaire/_delete_form.html.twig') }}
        </div>
    </div>
{% endblock %}